language: ruby
sudo: required
rvm:
  - 2.1
  - 2.2
  - 2.3.3

install:
  - sudo apt-get update -qq
  - sudo apt-get install libpcap-dev -qq
  - bundler install --path vendor/bundle --jobs=3 --retry=3
before_script:
  - sudo ip addr add ::1/64 scope host dev lo
  - /sbin/ifconfig
script:
  - bundler exec rake
  - rvmsudo bundle exec rake spec:sudo
